### ISSUE TITLE
slowmovie plugin

### ISSUE THREAD

**Issue by txoof** [txoof/epd_display#39]
add a slowmovie plugin that shows the Nth next frame from a movie file every time the screen is updated. See: https://github.com/TomWhitwell/SlowMovie

**Comment by txoof** [comment]
see thread: https://github.com/TomWhitwell/SlowMovie/issues/113#issuecomment-1027171353

**Comment by txoof** [comment]
needs a plugin that polls a configured path for whatever image is produced by SlowMovie. Plugin simply displays whatever the current image is when it comes around in the loop.

This is great for someone that wants to try their hand at building a plugin

**Comment by aaronr8684** [comment]
Added to #63
