### ISSUE TITLE
Support for Pimoroni Inky pHat

### ISSUE THREAD

**Issue by alemarengo** [txoof/epd_display#41]

**Comment by txoof** [comment]
@alemarengo I'd love to integrate support for the Inky!

I don't have access to any Inky pHats, but I do have a pretty good idea how to move forward with this. Would you be willing to work with me in developing a solution? This would involve some refactoring of the underlying [epdlib](https://github.com/txoof/epdlib), but it was built with modularity in mind, so it should be fairly straightforward.

The [InkyPhat library](https://github.com/pimoroni/inky) looks pretty easy to use and would make it possible to add color images to PaperPi.

**Comment by aaronr8684** [comment]
Hey @alemarengo, do you have some time to test the EPDLib changes to verify that the pHats are working as expected?
