### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by blbal** [txoof/epd_display#70]
In a number of places across documentation for this project (Plugins.md, step_by_step_instructions.md) the location of the configuration file is (incorrectly) referred to as `/etc/defaults/paperpi.ini` instead of `/etc/default/paperpi.ini`.  Presume this is a typo?

**Comment by blbal** [comment]
Sorry the link on the page sent me to the archived project.

**Comment by txoof** [comment]
Can you point me to the link that points to the archives version? I'd like to get rid of that.

**Comment by blbal** [comment]
Bottom of README.md:

```
**Software Bugs**
Please [open tickets at GitHub](https://github.com/txoof/epd_display/issues).
```
