### ISSUE TITLE
version `GLIBC_2.28' not found - Non Fixable on Raspberry Pi 3

### ISSUE THREAD

**Issue by nekopoolgithub** [txoof/epd_display#71]
Dear txoof,

I am trying to get your paperpi working on my 7.3 inch ePaper display from Waveshare. Though I know it might need some adaptation, however it is failing at start with the following message. It appears this modern lib used to compile is not yet officially available in armhf version, thus on Raspberry Pis.

`root@swag:~/paperpi/dist# ./paperpi
[2693] Error loading Python lib '/tmp/_MEIHEq9yk/libpython3.7m.so.1.0': dlopen: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/_MEIHEq9yk/libpython3.7m.so.1.0)`

Please let me know if that is a known issue, I can't figure out to find a suitable version. Official repo will only get you up to 2.24. See below my freshly installed RPi:

`oot@swag:~/paperpi/dist# ldd --version
ldd (Debian GLIBC 2.24-11+deb9u4) 2.24`

Many thanks for your help, and most of all for sharing all of this to the Internet.

A friend from France.

T.

**Comment by txoof** [comment]
@nekopoolgithub This version of PaperPi is deprecated and no longer under development. I suggest you move to the new version found here:
https://github.com/txoof/paperpi/

The new version of PaperPi supports more screens, will eventually support 7-color screens and supports most of the same plugins. The NodeRed plugin has not yet been migrated, but the rest are there.

If you want to test out the pre-release check out the development branch here: https://github.com/txoof/PaperPi/tree/development 

The remote installer for the development branch can be accessed with this curl: `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/txoof/PaperPi/I%2379_color_display/install/remote_install_development.sh)"`

Let me know if you run into any problems

**Comment by txoof** [comment]
@nekopoolgithub Any word on this? Can I close this ticket?

**Comment by nekopoolgithub** [comment]
Sorry sir, was lost in my tests. I tried the new version and face exactly the same issue on Raspberry Pi 3. There are no candidates at the required version in armhf proc.

**Comment by txoof** [comment]
@nekopoolgithub No problem at all. I understand how it can be.

Can you provide the following information for me:

- Verify which version you are trying to install -- are you using `https://github.com/txoof/epd_display` OR `https://github.com/txoof/paperpi`?
- Verify which OS you're using (use: `uname -a` and `lsb_release -a`) -- paste that in 
- Describe how you tried to install (e.g. `git clone` or `curl`)
- Paste the errors you're seeing
